### ISSUE TITLE
Dont use this

### ISSUE THREAD

**Issue by jameshackerbond** [Sigma-Production/PteroFreeStuffinstaller#58]
1. It's outdated & the support is bad
2. There is no backup feature (it dosent work)
3. No reverting back to the old panel
4. Most of the addons or theme will break your panel

**Comment by finnie2006** [comment]
instead of saying what is wrong you can help, we all have a life, you think me too?

Also there is a WORKING backup system and as an emergency solution you can always use the panel update.

also 2 and 3 are the same points

The problem is closed because of the tone used, come back with a different tone.
